version: "3"
services:
  mongodb:
    image: mongo:5.0.11
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
